
import pandas as pd
import numpy as np
from backtesting import Strategy, Backtest
import os
import sys
import json

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# from src.strategies.base import MoonDevStrategy # This was incorrect based on review


def generate_synthetic_stock_universe(n_stocks=100, n_days=500, seed=42):
    """
    Generates a synthetic universe of stock prices with some correlation.
    """
    np.random.seed(seed)
    dates = pd.date_range(start='2022-01-01', periods=n_days, freq='B')
    market_returns = np.random.randn(n_days) * 0.01
    stock_returns = np.random.randn(n_days, n_stocks) * 0.02
    total_returns = market_returns[:, np.newaxis] + stock_returns
    initial_prices = 100 + np.random.rand(n_stocks) * 100
    prices = initial_prices * np.exp(np.cumsum(total_returns, axis=0))
    df_prices = pd.DataFrame(prices, index=dates, columns=[f'Stock_{i}' for i in range(n_stocks)])
    return df_prices

def generate_synthetic_dtc_factor(prices_df, seed=42):
    """
    Generates a synthetic 'Days to Cover' factor for each stock.
    """
    np.random.seed(seed)
    n_days, n_stocks = prices_df.shape
    dtc = np.ones((n_days, n_stocks)) * 5
    dtc += np.random.randn(n_days, n_stocks).cumsum(axis=0) * 0.1
    dtc += np.random.randn(n_days, n_stocks) * 0.5
    dtc = np.maximum(dtc, 0.1)
    df_dtc = pd.DataFrame(dtc, index=prices_df.index, columns=prices_df.columns)
    return df_dtc


def simulate_factor_portfolio(prices_df, factor_df):
    """
    Simulates the cross-sectional, decile-based long-short portfolio strategy.
    Returns a single series representing the cumulative equity curve.
    """
    # Calculate daily returns for all stocks
    returns_df = prices_df.pct_change()

    # Align factor data with next day's returns
    # We rank based on today's factor to trade tomorrow's open
    factor_ranks = factor_df.shift(1).rank(axis=1, pct=True)

    # Identify top and bottom deciles
    long_signals = factor_ranks <= 0.1
    short_signals = factor_ranks >= 0.9

    # Calculate portfolio returns
    # Long leg: equal weight returns of stocks in the bottom decile
    long_returns = (returns_df * long_signals).mean(axis=1)

    # Short leg: equal weight returns of stocks in the top decile
    short_returns = (returns_df * short_signals).mean(axis=1)

    # Total portfolio return is long minus short
    portfolio_returns = long_returns - short_returns

    # Create the OHLC DataFrame for backtesting
    # We simulate a 'buy-and-hold' on this synthetic equity curve
    initial_equity = 100_000
    equity_curve = (1 + portfolio_returns).cumprod() * initial_equity

    ohlc_df = pd.DataFrame(index=equity_curve.index)
    ohlc_df['Open'] = equity_curve.shift(1).fillna(initial_equity)
    ohlc_df['High'] = equity_curve.shift(1).fillna(initial_equity) # Simplification for buy-and-hold
    ohlc_df['Low'] = equity_curve.shift(1).fillna(initial_equity)  # Simplification for buy-and-hold
    ohlc_df['Close'] = equity_curve
    ohlc_df['Volume'] = 100 # Placeholder volume

    return ohlc_df.dropna()


class DaysToCoverShortInterestMeanReversion(Strategy):
    """
    This strategy doesn't have complex logic itself. It simply buys and holds
    the equity curve generated by the cross-sectional simulation.
    The performance of this 'buy-and-hold' backtest directly reflects the
    performance of the factor model.
    """
    def init(self):
        # On the first bar, go long and hold until the end.
        pass

    def next(self):
        # This ensures the buy-and-hold is correctly registered in the stats.
        if self.position:
            self.position.close()
        self.buy()

if __name__ == '__main__':
    # 1. Generate synthetic data for a universe of stocks
    prices = generate_synthetic_stock_universe(n_stocks=200, n_days=1000)
    dtc_factor = generate_synthetic_dtc_factor(prices)

    # 2. Simulate the cross-sectional factor strategy to get an equity curve
    portfolio_equity_curve = simulate_factor_portfolio(prices, dtc_factor)

    # 3. Backtest the resulting equity curve with a simple buy-and-hold strategy
    bt = Backtest(portfolio_equity_curve, DaysToCoverShortInterestMeanReversion, cash=100_000, commission=0.0, finalize_trades=True)
    stats = bt.run()

    print("="*80)
    print("Days to Cover Short Interest Mean Reversion Strategy Simulation")
    print("="*80)
    print(stats)

    # 4. Save results
    results_dir = 'results'
    os.makedirs(results_dir, exist_ok=True)

    stats_dict = dict(stats)
    stats_dict.pop('_equity_curve', None)
    stats_dict.pop('_trades', None)

    with open(os.path.join(results_dir, 'temp_result.json'), 'w') as f:
        json.dump(stats_dict, f, indent=4, default=str)
    print(f"\nResults saved to {os.path.join(results_dir, 'temp_result.json')}")

    plot_filename = os.path.join(results_dir, 'days_to_cover_short_interest_mean_reversion.html')
    try:
        bt.plot(filename=plot_filename, open_browser=False)
        print(f"Plot saved to {plot_filename}")
    except Exception as e:
        print(f"Could not save plot: {e}")
