import pandas as pd
import pandas_ta as ta
import numpy as np
import json
import os
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

def PtaPSAR(high_series, low_series, close_series, af0=0.02, af=0.02, max_af=0.2):
    """
    Wrapper for pandas_ta.psar that returns a single numpy array for the SAR value
    as expected by backtesting.py's self.I().
    """
    psar = ta.psar(high=pd.Series(high_series), low=pd.Series(low_series), close=pd.Series(close_series), af0=af0, af=af, max_af=max_af)
    # Combine the long and short SAR values into a single series. The column names are dynamically generated by pandas_ta.
    psar_long_col = [col for col in psar.columns if col.startswith('PSARl')]
    psar_short_col = [col for col in psar.columns if col.startswith('PSARs')]
    if not psar_long_col or not psar_short_col:
        raise ValueError("Could not find PSAR long and short columns in the indicator output.")

    sar_values = np.where(psar[psar_long_col[0]].notna(), psar[psar_long_col[0]], psar[psar_short_col[0]])
    return sar_values

def generate_synthetic_data():
    """Generates synthetic data for testing the strategy."""
    print("Generating synthetic data...")
    n_points = 2000
    index = pd.to_datetime(pd.date_range('2023-01-01', periods=n_points, freq='15min'))
    price = 100 + pd.Series(np.random.randn(n_points).cumsum() * 0.1)
    price += np.sin(np.linspace(0, 200, n_points)) * 2
    data = pd.DataFrame({
        'Open': price, 'High': price * 1.005, 'Low': price * 0.995,
        'Close': price, 'Volume': np.random.randint(100, 1000, n_points)
    }, index=index)
    return data

class ParabolicSARStrategy(Strategy):
    """
    A trend-following strategy that uses the Parabolic SAR indicator.
    - Enters long when the price crosses above the PSAR.
    - Enters short when the price crosses below the PSAR.
    - Reverses position on opposite signal.
    """
    initial_af = 0.02
    step_af = 0.02
    max_af = 0.2

    def init(self):
        self.psar = self.I(
            PtaPSAR, self.data.High, self.data.Low, self.data.Close,
            af0=self.initial_af, af=self.step_af, max_af=self.max_af
        )

    def next(self):
        if crossover(self.data.Close, self.psar):
            self.position.close()
            self.buy()
        elif crossover(self.psar, self.data.Close):
            self.position.close()
            self.sell()

if __name__ == '__main__':
    data_path = 'data/BTC-USD-15m.csv'

    if os.path.exists(data_path):
        print(f"Loading data from: {data_path}")
        try:
            data = pd.read_csv(
                data_path, index_col='datetime', parse_dates=True, header=0,
                names=['datetime', 'Open', 'High', 'Low', 'Close', 'Volume', 'Unnamed'],
                usecols=['datetime', 'Open', 'High', 'Low', 'Close', 'Volume']
            )
        except Exception as e:
            print(f"Error loading CSV, falling back to synthetic data: {e}")
            data = generate_synthetic_data()
    else:
        print(f"Data file not found at '{data_path}'.")
        data = generate_synthetic_data()

    bt = Backtest(data, ParabolicSARStrategy, cash=100_000, commission=.002)

    print("Running backtest with default parameters...")
    stats = bt.run()

    os.makedirs('results', exist_ok=True)

    def sanitize_stats(stats):
        sanitized = {}
        for key, value in stats.items():
            if isinstance(value, (pd.Series, pd.DataFrame)): continue
            if isinstance(value, (np.floating, np.integer)):
                sanitized[key] = float(value) if np.isfinite(value) else None
            elif isinstance(value, int): sanitized[key] = int(value)
            elif isinstance(value, pd.Timestamp): sanitized[key] = value.isoformat()
            elif isinstance(value, pd.Timedelta): sanitized[key] = str(value)
            elif pd.isna(value): sanitized[key] = None
            elif key.startswith('_'): continue
            else: sanitized[key] = value
        return sanitized

    final_stats = sanitize_stats(stats)

    with open('results/temp_result.json', 'w') as f:
        json.dump(final_stats, f, indent=2)

    print("Backtest results saved to results/temp_result.json")
    print(stats)

    try:
        plot_filename = 'results/strategy_2734b8d5219d.html'
        bt.plot(filename=plot_filename)
        print(f"Backtest plot saved to {plot_filename}")
    except Exception as e:
        print(f"Could not generate plot: {e}")
